### ISSUE TITLE
Clarification for the limitation of images size

### ISSUE THREAD

**Issue by bg43179** [markable-dev/markable-api-docs#13]
It's really confusing. Should add a clarification between these two.
-> We support 100px for search. But only 224px+ for indexing

• Search
<img width="538" alt="screenshot 2018-08-20 at 11 17 53" src="https://user-images.githubusercontent.com/11611465/44355651-ce598380-a472-11e8-91e3-183744311640.png">

• Index (Catalog Item)
<img width="529" alt="screenshot 2018-08-20 at 11 32 34" src="https://user-images.githubusercontent.com/11611465/44355666-d4e7fb00-a472-11e8-9cf4-e239d00c3dbd.png">

**Comment by troubleDicky** [comment]
@huffmsa @cggaurav can we modify/change the indexing minimum to be 100px as well? this is a request from Joy

**Comment by cggaurav** [comment]
Fixed with 8a3a547..cd37062
